### Health check
GET http://localhost:3000/healthz HTTP/1.1

### Create user
POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "firstName": "Adam",
    "lastName": "Bendler",
    "email": "Adam.B@sadfd.com",
    "password": "test"
}

### Get all users
GET http://localhost:3000/api/users HTTP/1.1